name: 'fraud'
version: '1.0.0'
config-version: 2
profile: 'fraud'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fraud:
    staging:
      +materialized: view
    marts:
      +materialized: table
